libraryDependencies += "org.typelevel" %% "cats-core" % "1.6.0"
libraryDependencies += "org.typelevel" %% "cats-effect" % "1.3.0"
libraryDependencies += "org.tpolecat" %% "skunk-core" % "0.0.3"
libraryDependencies += "com.nrinaudo" %% "kantan.csv" % "0.5.0"
libraryDependencies += "com.nrinaudo" %% "kantan.csv-cats" % "0.5.0"
