version: "3"
services:
  db:
    image: "postgres:11.2-alpine"
    environment:
      POSTGRES_USER: "funcional"
    ports:
      - "5432:5432"
  etl:
    image: "dataloader:0.1"
    environment:
      DB_HOST: database
    links:
      - "db:database"
    volumes:
      - ./shared_files:/opt/docker/output


