version: "3"
services:
  db:
    image: "postgres:11.2-alpine"
    environment:
      POSTGRES_USER: "funcional"
    ports:
      - "5432:5432"
  rest-service:
    image: "rest-service:0.1"
    environment:
      DB_HOST: database
    links:
      - "db:database"
    ports:
      - "8080:8080"
    volumes:
      - ./shared_files:/opt/docker/output
    depends_on:
      - db
  apitest:
      image: "apitest:0.1"
      environment:
        REST_URL: rest-url
      links:
        - "rest-service:rest-url"
      depends_on:
        - db
        - rest-service
      volumes:
        - ./assets:/opt/docker/input
